<?php
/**
 * Scheduled Report Plain Text Email Template (P4-010)
 *
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\ScheduledReport $report
 * @var array $data
 * @var string $orgName
 * @var string $periodLabel
 * @var string $siteName
 * @var string $manageUrl
 */

$summary = $data['summary'] ?? [];
$monitors = $data['monitors'] ?? [];
$slaStatus = $data['sla_status'] ?? [];
$period = $data['period'] ?? [];
$frequencyLabel = ($period['frequency'] ?? 'weekly') === 'monthly' ? 'Monthly' : 'Weekly';
?>
<?= $frequencyLabel ?> Uptime Report - <?= $orgName ?>

Period: <?= $periodLabel ?>

========================================
SUMMARY
========================================
Total Monitors:    <?= (int)($summary['total_monitors'] ?? 0) ?>

Average Uptime:    <?= number_format($summary['avg_uptime'] ?? 0, 2) ?>%
Avg Response Time: <?= number_format($summary['avg_response_time'] ?? 0, 0) ?> ms
Total Incidents:   <?= (int)($summary['total_incidents'] ?? 0) ?>


========================================
MONITOR DETAILS
========================================
<?php foreach ($monitors as $mon): ?>
<?= h($mon['name']) ?>

<?php if ($report->include_uptime && $mon['uptime'] !== null): ?>
  Uptime: <?= number_format($mon['uptime'], 2) ?>%
<?php endif; ?>
<?php if ($report->include_response_time && $mon['avg_response'] !== null): ?>
  Avg Response: <?= number_format($mon['avg_response'], 0) ?> ms
<?php endif; ?>
<?php if ($report->include_incidents): ?>
  Incidents: <?= (int)$mon['incidents'] ?>

<?php endif; ?>
  Status: <?= ucfirst($mon['status']) ?>

---
<?php endforeach; ?>

<?php if ($report->include_sla && !empty($slaStatus)): ?>
========================================
SLA STATUS
========================================
<?php foreach ($slaStatus as $sla): ?>
<?= h($sla['name']) ?> (<?= h($sla['monitor_name']) ?>)
  Target: <?= number_format($sla['target'], 2) ?>%
  Actual: <?= number_format($sla['actual'], 2) ?>%
  Status: <?= ucfirst($sla['status']) ?>

---
<?php endforeach; ?>
<?php endif; ?>

--
This report was automatically generated by <?= $siteName ?>.
<?php if (!empty($manageUrl)): ?>
Manage report settings: <?= $manageUrl ?>

<?php endif; ?>
